# Generated by Django 3.1.5 on 2021-04-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='TodoUser',
        ),
    ]
